---
title: Covid Collab
author: Callum Stewart
email: callum.stewart@kcl.ac.uk
description: Desc.
baseurl: "/"
url: https://covid-collab.org
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
- jekyll-seo-tag
